/*
   -- ESP32-S3_RemoteXY_BLE_LED_Control --
   
   To compile this code using RemoteXY library 4.1.8 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__ESP32CORE_BLE
#include <Arduino.h>
#include <BLEDevice.h>

// RemoteXY connection settings 
#define REMOTEXY_BLUETOOTH_NAME "RemoteXY_BLE_LED_Control"
#define REMOTEXY_ACCESS_PASSWORD ""   // No password

#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 64 bytes V19 
  { 255,1,0,0,0,57,0,19,0,0,0,82,101,109,111,116,101,88,89,95,
  76,69,68,95,83,119,105,116,99,104,0,31,1,106,200,1,1,1,0,10,
  38,83,29,29,48,4,26,31,76,69,68,32,79,78,0,31,76,69,68,32,
  79,70,70,0 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  uint8_t pushSwitch_01;  // =1 if state is ON, else =0, from 0 to 1

    // other variable
  uint8_t connect_flag;   // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////


//  HARDWARE SETUP
const int PIN_LED = 2;            // External LED
const int PIN_RGB_BUILTIN = 38;   // Built-in RGB LED (NeoPixel)


void setup() 
{
  RemoteXY_Init ();  // initialization by macros 
  
  // Initialize External LED
  pinMode(PIN_LED, OUTPUT);
  digitalWrite(PIN_LED, LOW);     // Ensure OFF

  // Initialize Built-in RGB LED
      // Most S3 RGBs are "Smart LEDs" that need a signal, not just HIGH/LOW.
      // neopixelWrite(PIN, Red, Green, Blue) is a built-in ESP32 function.
      // We send 0,0,0 to force it OFF at startup.
  neopixelWrite(PIN_RGB_BUILTIN, 0, 0, 0);

  // Debugging (Optional)
  Serial.begin(115200);
  delay(500);
  Serial.println(">> Bluetooth Started. Waiting for App connection...");

  // TODO you setup code
  
}

void loop() 
{ 
  // Handle Bluetooth traffic
  RemoteXYEngine.handler ();   
   
  // --- LED LOGIC ---
  // Connect the Virtual Switch to the Physical LED
  if (RemoteXY.pushSwitch_01 != 0) {
    // SWITCH IS ON
    digitalWrite(PIN_LED, HIGH);                // Turn External LED ON
    neopixelWrite(PIN_RGB_BUILTIN, 0, 50, 0);   // Turn RGB LED ON (Green Color)
                                                // neopixelWrite(Pin, Red, Green, Blue); Brightness 0-255
  } else {
    // SWITCH IS OFF
    digitalWrite(PIN_LED, LOW);                 // Turn External LED OFF
    neopixelWrite(PIN_RGB_BUILTIN, 0, 0, 0);    // Turn RGB LED OFF
  }

  // TODO you loop code
  // use the RemoteXY structure for data transfer
  // do not call delay(), use instead RemoteXYEngine.delay() 

}